### ISSUE TITLE
Update starter to Gradle 7 and XP 7.8

### ISSUE THREAD

**Issue by reisfmb** [enonic/starter-react4xp#171]
https://github.com/orgs/enonic/repositories?q=starter&type=public&language=&sort=

All starters should use Gradle 7  (latest) wrapper
- https://github.com/enonic/starter-headless/blob/master/gradle/wrapper/gradle-wrapper.properties#L3
- Don't use `compile`. Use `implementation` https://github.com/enonic/starter-headless/blob/master/build.gradle#L16
- Don't use `jcenter`. Use `mavenCentral`
- Verify that CLI still can use such starters
- There is a very low risk to update starters to XP 7.8, and it should be done as well

Issue is similar to https://github.com/enonic/guide-my-first-app/issues/9

**Comment by reisfmb** [comment]
Been facing some problems with the build using Gradle 7.0:

```
> Task :react4xp_components FAILED
Execution optimizations have been disabled for task ':react4xp_components' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/home/bruno/Enonic/Work/Starters/starter-react4xp/node_modules/webpack/bin/webpack.js'. Reason: Task ':react4xp_components' uses this output of task ':npmInstall' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/home/bruno/Enonic/Work/Starters/starter-react4xp/package-lock.json'. Reason: Task ':react4xp_components' uses this output of task ':npmInstall' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[webpack-cli] SyntaxError: Invalid regular expression: /(\p{Uppercase_Letter}+|\p{Lowercase_Letter}|\d)(\p{Uppercase_Letter}+)/: Invalid escape
    at pathToArgumentName (/home/bruno/Enonic/Work/Starters/starter-react4xp/node_modules/webpack/lib/cli.js:66:4)
    at addFlag (/home/bruno/Enonic/Work/Starters/starter-react4xp/node_modules/webpack/lib/cli.js:170:16)
    at traverse (/home/bruno/Enonic/Work/Starters/starter-react4xp/node_modules/webpack/lib/cli.js:243:21)
    at traverse (/home/bruno/Enonic/Work/Starters/starter-react4xp/node_modules/webpack/lib/cli.js:299:23)
    at traverse (/home/bruno/Enonic/Work/Starters/starter-react4xp/node_modules/webpack/lib/cli.js:248:24)
    at Object.getArguments (/home/bruno/Enonic/Work/Starters/starter-react4xp/node_modules/webpack/lib/cli.js:308:2)
    at WebpackCLI.getBuiltInOptions (/home/bruno/Enonic/Work/Starters/starter-react4xp/node_modules/webpack-cli/lib/webpack-cli.js:890:41)
    at makeCommand (/home/bruno/Enonic/Work/Starters/starter-react4xp/node_modules/webpack-cli/lib/webpack-cli.js:1051:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react4xp_components'.
> Process 'command 'node'' finished with non-zero exit value 2
```
From what I've read, other ppl are facing same thing:
https://github.com/JLLeitschuh/ktlint-gradle/issues/457

Tried to build with **Gradle 7.2** and it worked.

**Comment by reisfmb** [comment]
Build failed with Gradle 7.3 and worked with 7.3.1
