### ISSUE TITLE
Upgrade to @enonic/react4xp@3.0.18 breaks build on Windows

### ISSUE THREAD

**Issue by poi33** [enonic/starter-react4xp#268]
```
> Task :react4xpComponents

> @enonic/react4xp@3.0.18 webpack:components
> npx webpack --config dist/webpack.config.components.js "--env" "DIR_PATH_ABSOLUTE_PROJECT=C:\\Users\\pkw\\Documents\\StandAlone\\myproject2" "--env" "BUILD_ENV=production" "--env" "VERBOSE=false"

react4xp-build-entriesandchunks used entrySets (array[1]): [
  {
    "sourcePath": "C:\\Users\\pkw\\Documents\\StandAlone\\myproject2\\src\\main\\resources\\site",
    "sourceExtensions": [
      "jsx",
      "tsx"
    ],
    "targetSubDir": "site"
  }
]
[webpack-cli] Error: react4xp-build-components can't continue - no entries were found (entries={}). Tip: the combination of entryDirs and entryExtStringArrayensions in react4xp.properties was resolved to the entrySets above. Check the content of those directories, with those file extensions. Add entry source files, adjust react4xp.properties, or run the build with isVerbose=true in react4xp.properties for more info.
    at module.exports (C:\Users\pkw\Documents\StandAlone\myproject2\node_modules\@enonic\react4xp\dist\webpack.config.components.js:215:15)
    at loadConfigByPath (C:\Users\pkw\Documents\StandAlone\myproject2\node_modules\webpack-cli\lib\webpack-cli.js:1747:27)
    at async Promise.all (index 0)
    at async WebpackCLI.loadConfig (C:\Users\pkw\Documents\StandAlone\myproject2\node_modules\webpack-cli\lib\webpack-cli.js:1765:29)
    at async WebpackCLI.createCompiler (C:\Users\pkw\Documents\StandAlone\myproject2\node_modules\webpack-cli\lib\webpack-cli.js:2187:18)
    at async WebpackCLI.runWebpack (C:\Users\pkw\Documents\StandAlone\myproject2\node_modules\webpack-cli\lib\webpack-cli.js:2323:16)
    at async Command.<anonymous> (C:\Users\pkw\Documents\StandAlone\myproject2\node_modules\webpack-cli\lib\webpack-cli.js:1060:13)
    at async Promise.all (index 1)
    at async Command.<anonymous> (C:\Users\pkw\Documents\StandAlone\myproject2\node_modules\webpack-cli\lib\webpack-cli.js:1674:7)
npm ERR! code 2
npm ERR! path C:\Users\pkw\Documents\StandAlone\myproject2\node_modules\@enonic\react4xp
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npm run webpack:components -- --env DIR_PATH_ABSOLUTE_PROJECT=C:\Users\pkw\Documents\StandAlone\myproject2 --env BUILD_ENV=production --env VERBOSE=false
```

**Comment by ComLock** [comment]
The error is probably in getEntries or buildEntriesToSubfolder. Someone with windows has to look at that.
